import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './component/header'
import Informetion from './component/informetion'
import Menuber from './component/menuber'
import Footer from './component/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className="inter.className">
        <Header />
        <div className="lg:px-20">
          <Informetion />
        </div>
        <Menuber />
        {children}
        <div className='pt-8'>
          <Footer />
        </div>
        </body>
    </html>
  )
}
